"""address add in employee model

Revision ID: 3cb31e31c7c1
Revises: ed77c06fc294
Create Date: 2026-08-28 18:37:37.607548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cb31e31c7c1'
down_revision: Union[str, Sequence[str], None] = 'ed77c06fc294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('address', sa.String(), nullable=True))
    op.alter_column('employees', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'department',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'department',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('employees', 'address')
    # ### end Alembic commands ###
