"""add department_id to employees

Revision ID: 597edada736b
Revises: c654a3ff3cb4
Create Date: 2026-08-29 16:12:07.454148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '597edada736b'
down_revision: Union[str, Sequence[str], None] = 'c654a3ff3cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('department_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('employees_dept_id_fkey'), 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'departments', ['department_id'], ['id'])
    op.drop_column('employees', 'dept_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('dept_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key(op.f('employees_dept_id_fkey'), 'employees', 'departments', ['dept_id'], ['id'])
    op.drop_column('employees', 'department_id')
    # ### end Alembic commands ###
