"""add profile image column in employee table

Revision ID: b2c147670291
Revises: feb158e8f84b
Create Date: 2026-09-10 21:02:08.906746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2c147670291'
down_revision: Union[str, Sequence[str], None] = 'feb158e8f84b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('profile_image', sa.String(), nullable=True))
    op.alter_column('employees', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('employees', 'profile_image')
    # ### end Alembic commands ###
