"""relationship emp and Dept

Revision ID: c654a3ff3cb4
Revises: a5cb86f902aa
Create Date: 2026-08-28 23:17:47.736794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c654a3ff3cb4'
down_revision: Union[str, Sequence[str], None] = 'a5cb86f902aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('dept_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'departments', ['dept_id'], ['id'])
    op.drop_column('employees', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'dept_id')
    # ### end Alembic commands ###
